networks:
  network:
    driver: bridge

services:
  global_test:
    container_name: global_test
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - ./.env
    environment:
      DB_HOST: db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "8000:8000"
    networks:
      - network
    depends_on:
      - db
  db:
    container_name: postgres_db
    image: postgres:17
    restart: always
    environment:
      DB_HOST: db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./services/postgres_data:/var/lib/postgresql/data
    networks:
      - network
    ports:
      - "5506:5432"
